### ISSUE TITLE
Erlang apt PPA does not work

### ISSUE THREAD

**Issue by BatmanAoD** [gleam-lang/gleam#1693]
This issue describes a problem I ran into while attempting to install Erlang on Ubuntu (on WSL): https://github.com/elixir-lang/elixir-lang.github.com/issues/1575

Specifically, Erlang's PPA (their hosted source for Debian/Ubuntu packages) appears to be broken, at least for Ubuntu 22.04 (Jammy).

Since Gleam's installation instructions recommend using the PPA, it might be preferable to recommend a different approach. Unfortunately, I'm not sure what the most straightforward/correct path would actually be, though I did add a comment on the Elixir issue thread describing my installation approach (downloading the `.deb` file directly and installing with `apt`).

**Comment by lpil** [comment]
Thank you! I'm not sure what the right thing to recommend is here. I am surprised that they are not producing packages for the latest version of the operating system.

**Comment by lpil** [comment]
I believe this has been resolved

**Comment by BatmanAoD** [comment]
It's actually still not working (tested this time with Ubuntu 23.04 on a VM on Mac OS), but for some reason the originally-linked Erlang issue has been replaced with a different one: https://github.com/esl/packages/issues/15

The issue thread mentions using `binaries2.erlang-solutions.com` instead of `binaries.erlang-solutions.com`, but that doesn't seem to work for Ubuntu `lunar`; maybe it works for 22, though.

The last comment in the thread implies that RabbitMQ maintains working repos; maybe people should just be pointed there instead of toward the official Erlang repos?

**Comment by lpil** [comment]
Excellent, thank you. Would you like to make a pull request? Being familiar with this process.

**Comment by BatmanAoD** [comment]
I just installed Erlang using the [RabbitMQ instructions](https://www.rabbitmq.com/install-debian.html#apt-cloudsmith), and it went fine.

But, come to think of it, there's not a ton of benefit in doing so, because the Gleam installation page doesn't actually have an officially recommended `apt` source for Gleam itself. So I installed `asdf` and installed Gleam that way.

...so maybe Gleam should just recommend `asdf` for Debian/Ubuntu users?

**Comment by lpil** [comment]
asdf is quite complex, doesn't do automatic patching, and takes a long time to install Erlang as it compiles from source, so I think in many situations installing using the OS package manager is much preferred.

I'm a huge fan of it but I think it's best suited to development usage and for folks with some familiarity with CLI tools and C compilation.
